/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.connect;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClockThread;
import model.HoaDon;
import model.MonAn;
import model.MonAnDAO;
import model.HoaDonDao;
import static model.HoaDonDao.prepare;

/**
 *
 * @author hongl
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setLocationRelativeTo(null);
    }
    int i=0;
    HoaDonDao hdDao = new HoaDonDao();
    HoaDon h = new HoaDon();
    ArrayList<MonAn> list = new ArrayList<>();
    ArrayList<HoaDon> listHD = new ArrayList<>();
    //Lay ten mon an

    public ArrayList<MonAn> ShowTenMonAn() throws SQLException {
        list.clear();
        Connection conn = connect.getConnect();
        Statement st = null;
        ResultSet rs = null;

        String sql = "select * from qlmonan";
        st = conn.createStatement();
        rs = st.executeQuery(sql);
        frmMain m = new frmMain();
        while (rs.next()) {
            MonAn f = new MonAn();
            f.setIdMonAn(rs.getInt("idMon"));
            f.setTenMon((rs.getString("tenMon")));
            f.setGia((rs.getFloat("gia")));
            txtMonAn.addItem(rs.getString("tenMon"));
            list.add(f);
        }
        return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnXoa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblTong = new javax.swing.JLabel();
        cboLoaiBan = new javax.swing.JComboBox<>();
        cboSoBan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMonAn = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnIn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMonAn = new javax.swing.JComboBox();
        btnLuu = new javax.swing.JButton();
        lblTong1 = new javax.swing.JLabel();
        jdNgay = new com.toedter.calendar.JDateChooser();
        btn_quaylai = new javax.swing.JButton();
        btnClock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Tổng:");

        lblTong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTong.setText("VNĐ");

        cboLoaiBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboLoaiBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mang ve", "Su dung ban" }));
        cboLoaiBan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoaiBanItemStateChanged(evt);
            }
        });
        cboLoaiBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboLoaiBanMouseClicked(evt);
            }
        });
        cboLoaiBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiBanActionPerformed(evt);
            }
        });

        cboSoBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboSoBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bàn 1", "Bàn 2", "Bàn 3", "Bàn 4", "Bàn 5", "Bàn 6" }));
        cboSoBan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSoBanItemStateChanged(evt);
            }
        });
        cboSoBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboSoBanMouseClicked(evt);
            }
        });

        tbMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên món ăn", "Giá"
            }
        ));
        tbMonAn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbMonAnAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMonAnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbMonAn);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Ngày:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Sô bàn:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Loại:");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Quản lý nhà hàng");

        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        btnIn.setText("In hóa đơn");
        btnIn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tên món ăn:");

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Price list_1.png"))); // NOI18N
        btnLuu.setText("Lưu bàn");
        btnLuu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        lblTong1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTong1.setText("0.0");

        btn_quaylai.setBackground(new java.awt.Color(204, 204, 204));
        btn_quaylai.setText("Quay Lai");
        btn_quaylai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_quaylai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_quaylaiMouseClicked(evt);
            }
        });

        btnClock.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClock.setText("Clock");
        btnClock.setBorder(null);
        btnClock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClockMouseClicked(evt);
            }
        });
        btnClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(48, 48, 48)
                                .addComponent(lblTong1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboLoaiBan, 0, 154, Short.MAX_VALUE)
                                    .addComponent(jdNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMonAn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cboSoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(106, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClock, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jdNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboLoaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboSoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblTong1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     MonAnDAO maDao = new MonAnDAO();
//     public MonAn getModel(){
//        MonAn ma=new MonAn();
//        ma.setIdMonAn(Integer.parseInt(txtMa.getText()));
//        ma.setTenMon(txtTen.getText());
//        ma.setGia(Float.parseFloat(txtGia.getText()));
//        return ma;
//       
//    }
//     public void reset(){
//         txtGia.setText("");
//         txtMa.setText("");
//         txtTen.setText("");
//     }
    SimpleDateFormat date_format = new SimpleDateFormat("yyyy/MM/dd");

    public void setTable() throws SQLException {
        maDao.ShowAll();
        DefaultTableModel model = (DefaultTableModel) tbMonAn.getModel();
        model.setRowCount(0);
        model.setNumRows(0);
        for (MonAn object : maDao.Show()) {
            model.addRow(new Object[]{object.getTenMon(), object.getGia()});
        }
    }

    public void setTableByFile(ArrayList<MonAn> ma) throws SQLException {

        DefaultTableModel model = (DefaultTableModel) tbMonAn.getModel();
        model.setRowCount(0);
        model.setNumRows(0);
        for (MonAn object : ma) {
            model.addRow(new Object[]{object.getTenMon(), object.getGia()});
        }
    }
    //Tinh tien 

    public void calMoney() {
        float columCount = tbMonAn.getRowCount();
        float sum = 0;
        for (int i = 0; i < columCount; i++) {
            sum += Float.parseFloat(tbMonAn.getValueAt(i, 1) + "");
        }
        lblTong1.setText(sum + "");
    }
    //Kiem tra rong 

    //Hien thi mon an cho menu thuc don
    public void ShowMenu() throws SQLException {
        list.clear();
        Connection conn = connect.getConnect();
        Statement st = null;
        ResultSet rs = null;
        String ten = null;
        float gia = (float) 0.0;
        String sql = "SELECT tenMon, gia FROM `qlmonan` WHERE tenMon='" + txtMonAn.getSelectedItem().toString() + "' LIMIT 1";
        st = conn.createStatement();
        rs = st.executeQuery(sql);

        while (rs.next()) {
            MonAn f = new MonAn();
            f.setTenMon((rs.getString("tenMon")));
            f.setGia((rs.getFloat("gia")));
            ten = rs.getString("tenMOn");
            gia = rs.getFloat("gia");
            list.add(f);
        }
        DefaultTableModel model = (DefaultTableModel) tbMonAn.getModel();
        model.addRow(new Object[]{ten, gia});
    }

    //Xoa dong theo click
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) tbMonAn.getModel();
            int selectedRowIndex = tbMonAn.getSelectedRow();
            model.removeRow(selectedRowIndex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn đúng món ăn đẻ xóa!");
        }
        calMoney();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            ShowMenu();
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        calMoney();
    }//GEN-LAST:event_btnThemActionPerformed
    public HoaDon getModel() {
        HoaDon h = new HoaDon();
        SimpleDateFormat spd = new SimpleDateFormat("YYYY/MM/dd");
        h.setNgay(spd.format(jdNgay.getDate()));
        h.setLoai(cboLoaiBan.getSelectedItem().toString());
        h.setTong(Float.parseFloat(lblTong1.getText()));
        return h;
    }
    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed

        int dem = 0;
        try {
            listHD = hdDao.ThongKe();
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (Float.parseFloat(lblTong1.getText()) == 0.0) {
            JOptionPane.showMessageDialog(this, "Bạn phải thêm món ăn");
        } else {
            try {
                for (int i = 0; i < listHD.size(); i++) {
                    dem++;
                }
                int i = hdDao.layMaTheoTen(txtMonAn.getSelectedItem().toString());
                hdDao.AddHoaDon(dem + 1, getModel(), i);
            } catch (SQLException ex) {
                System.out.println("Error: " + ex);
            } catch (Exception ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         int i=cboSoBan.getSelectedIndex()+1;
        try {
            hdDao.ClearFile("ban"+i+".txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        cboLoaiBan.setSelectedIndex(0);
        btnLuu.setEnabled(false);
        lblTong1.setText("0");
        cboSoBan.setSelectedIndex(0);
        DefaultTableModel model = (DefaultTableModel) tbMonAn.getModel();
        model.setRowCount(0);
        model.setNumRows(0);
       
        
        
    }//GEN-LAST:event_btnInActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ClockThread th=new ClockThread(btnClock);
         th.start();
        try {
            // TODO add your handling code here:
            ShowTenMonAn();
            cboSoBan.setEnabled(false);
            btnLuu.setEnabled(false);
        } catch (SQLException ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void tbMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMonAnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tbMonAnMouseClicked

    private void tbMonAnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbMonAnAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_tbMonAnAncestorAdded

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLuuActionPerformed

    private void cboLoaiBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiBanActionPerformed
        // TODO add your handling code here:
        if (cboLoaiBan.getSelectedIndex() == 0) {
            cboSoBan.setEnabled(false);
        } else {
            cboSoBan.setEnabled(true);
            btnLuu.setEnabled(true);

        }
    }//GEN-LAST:event_cboLoaiBanActionPerformed

    private void cboSoBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboSoBanMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cboSoBanMouseClicked

    private void cboSoBanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSoBanItemStateChanged
        // TODO add your handling code here:
        calMoney();
        int tableIndex = cboSoBan.getSelectedIndex() + 1;
        ArrayList<MonAn> foodList = new ArrayList<>();
        try {
            foodList = hdDao.ReadTableByFile("ban" + tableIndex + ".txt");

        } catch (IOException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            setTableByFile(foodList);
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboSoBanItemStateChanged

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:

        int tableIndex = cboSoBan.getSelectedIndex() + 1;
        ArrayList<MonAn> listFood = new ArrayList<>();
      
        for (int i = 0; i < tbMonAn.getRowCount(); i++) {
            MonAn ma = new MonAn(i, tbMonAn.getValueAt(i, 0).toString(), Float.parseFloat(tbMonAn.getValueAt(i, 1).toString()));
            listFood.add(ma);
        }
        try {
            hdDao.WriteTable("ban" + tableIndex + ".txt", listFood);

        } catch (IOException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        cboLoaiBan.setSelectedIndex(0);
        btnLuu.setEnabled(false);
        lblTong1.setText("0");
        cboSoBan.setSelectedIndex(0);
        DefaultTableModel model = (DefaultTableModel) tbMonAn.getModel();
        model.setRowCount(0);
        model.setNumRows(0);
    }//GEN-LAST:event_btnLuuMouseClicked

    private void cboLoaiBanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoaiBanItemStateChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cboLoaiBanItemStateChanged

    private void cboLoaiBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboLoaiBanMouseClicked
        // TODO add your handling code here:
          if(cboLoaiBan.getSelectedIndex()==0){
        DefaultTableModel model = (DefaultTableModel) tbMonAn.getModel();
        model.setRowCount(0);
        model.setNumRows(0);
        lblTong1.setText("0");
        }
          else if(cboLoaiBan.getSelectedIndex()==1){
        calMoney();
        int tableIndex = cboSoBan.getSelectedIndex() + 1;
        ArrayList<MonAn> foodList = new ArrayList<>();
        try {
            foodList = hdDao.ReadTableByFile("ban" + tableIndex + ".txt");

        } catch (IOException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            setTableByFile(foodList);
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
          }
    }//GEN-LAST:event_cboLoaiBanMouseClicked

    private void btn_quaylaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quaylaiMouseClicked
        // TODO add your handling code here:
        frm_menu fm=new frm_menu();
        fm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_quaylaiMouseClicked

    private void btnClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClockActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnClockActionPerformed

    private void btnClockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClockMouseClicked
        // TODO add your handling code here:
        
        i++;
        if(i%2==0){
            btnClock.setBackground(Color.GREEN);
        }
        else{
            btnClock.setBackground(Color.cyan);
        }
    }//GEN-LAST:event_btnClockMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClock;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btn_quaylai;
    private javax.swing.JComboBox<String> cboLoaiBan;
    private javax.swing.JComboBox<String> cboSoBan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdNgay;
    private javax.swing.JLabel lblTong;
    private javax.swing.JLabel lblTong1;
    private javax.swing.JTable tbMonAn;
    private javax.swing.JComboBox txtMonAn;
    // End of variables declaration//GEN-END:variables

}
